### ISSUE TITLE
Feature Request: Hash current mod version, skip downloading if it matches latest

### ISSUE THREAD

**Issue by 5TXdYWK** [BeamMP/BeamMP-Launcher#11]
There's no need for the mod to be downloaded every single time someone launches BeamMP. This could probably save you a decent amount of money in bandwidth.

**Comment by Anonymous-275** [comment]
Hello! Already on the roadmap! Now the launcher doesn't redownload anything that matches 1 to 1 on what the server already has.

**Comment by Anonymous-275** [comment]
Please reopen if this persits in 2.1.0
