### ISSUE TITLE
How to setup project in Visual Studio

### ISSUE THREAD

**Issue by JustDesoroxxx** [BeamMP/BeamMP-Launcher#12]
Hi,

How could I open the project in Visual Studio, I already have the required dependencies now I would like some info on how to open the project in visual studio?

**Comment by Anonymous-275** [comment]
> Hi,
> 
> How could I open the project in Visual Studio, I already have the required dependencies now I would like some info on how to open the project in visual studio?

Make sure you have cmake installed in the visual studio installer, install vcpkg and use it for the dependencies, make sure you set the project settings in visual studio to load vcpkg cmake (comment in cmakelists.txt) and it should just work. Visual studio should be capable to load cmake projects.
