### ISSUE TITLE
not include hash in cached server mods file names 

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [BeamMP/BeamMP-Launcher#154]
one can get their storage filled up by 50 copies of the same mod, each slightly different with another, if you play a server with mods that recieves update, or you develope your own server mods and you actually tests them

since mods can get as big as several GBs, id say this is worth dealing with

**Comment by O1LER** [comment]
Launcher is not removing stale mods, resulting in the resource folder getting filled with copies of each version of a mod

![image-46](https://github.com/user-attachments/assets/a6003d2e-af58-4e8c-94ae-198a5b506d3e)

**Comment by WiserTixx** [comment]
This is intentional behaviour, but we've thought of a way to combat this. See #158
