### ISSUE TITLE
How to launch a game on DirectX?

### ISSUE THREAD

**Issue by jjjadeRRR** [BeamMP/BeamMP-Launcher#159]
BeamMP launches BeamNG on Vulkan which works very badly on my pc with Fedora Linux. In full screen mode there screen are flickers, and the interface does not work correctly. I tried to change in the settings file Vulkan on DirectX, but it didn't work and BeamNG still launched on Vulkan. How can this be fixed? The pre-launch window BeamNG does not appear.

**Comment by WiserTixx** [comment]
You can start the launcher with the `--no-launch` command line argument, and then proceed to open the game in DirectX.

**Comment by O1LER** [comment]
But the proton version also needs a way to access the natives userfolder

Either create a symlink in the proton userfolder pointing to the native one

or use the beamNG support tools to choose a different location for the proton userfolder.

Reason being, the native beamMP launcher will always write mods into the native userfolder

**Comment by jjjadeRRR** [comment]
Thank you

**Comment by jjjadeRRR** [comment]
Thank you
