### ISSUE TITLE
[Feature Request] Interact with game files properly on Proton or Linux

### ISSUE THREAD

**Issue by Gideon-Felt** [BeamMP/BeamMP-Launcher#17]
**Is your feature request related to a problem? Please describe.**
I may be able to install BeamMP on Proton or Wine. Still, upon launch, the terminal prompt goes into a blipping loop and says something about running on Linux/Proton and unable to find the game files, but says that it patched 100% which is obviously false.

**Describe the solution you'd like**
Enable at least with proton for the Patcher/Launcher to locate the game files in proton, as an alternative game location.

**Describe alternatives you've considered**
I wouldn't think a Linux specific launcher would be necessary, but that could be a thing, though is unreasonable, since the game is built for Windows and runs perfectly on Proton, so the alternative game files location would be the better solution since BeamMP installs and runs fine under proton, it's just incapable of finding the files to patch.

**Additional context**
This would also be a solution for Steam Deck players, where the game runs quite well.

**Comment by lionkor** [comment]
Hi! For the next version of the launcher, we are trying to make linux work out of the box. Right now, the solution is to run the launcher in the wineprefix of the game, that usually works okay. It then needs a few more little registry patches, sometimes.

Im definitely onboard with this request!

**Comment by GreatHaop** [comment]
Right now it breaks when running with Steam installed in wine.
I have to write a script as a workaound
```
@echo off
set USER=
/path/to/beammp.exe
```

**Comment by GreatHaop** [comment]
> Right now it breaks when running with Steam installed in wine. I have to write a script as a workaound
> 
> ```
> @echo off
> set USER=
> /path/to/beammp.exe
> ```

This workaround will make BeamMP-Launcher thinking that is is not running on wine and skip LinuxPatch() function

https://github.com/BeamMP/BeamMP-Launcher/blob/f6065a1c00ed172345a307e3262a84cfb0b302c4/src/Startup.cpp#L130

**Comment by yungslime** [comment]
+1 on giving users the option to specify their own paths and/or to manually override the automatic linux-specific behaviors. I just installed the game + BeamMP on a Mac via CrossOver and this was the only thing preventing the install from being as seamless as it would have been on a Windows machine. 

If the launcher hadn't tried to do anything special at all and instead just opted to do everything as if it were running on a real Windows machine, this would not have been an issue. (Thank you [GreatHaop](https://github.com/GreatHaop) for the USER-variable tip.)

**Comment by Anonymous-275** [comment]
paths in config is implemented in V3 branch, to be refined as more testing is conducted :)

**Comment by ich777** [comment]
@Anonymous-275 any progress on this? Is there somewhere a V3 preview to download from maybe you could upload a binary to the Releases marked as Pre-Release...?
I'm really curious how this work on the Steam Deck.

**Comment by Anonymous-275** [comment]
Please reopen if this persits in 2.1.0

**Comment by lionblaze55** [comment]
I am getting this issue using the newest version of proton and flatpaked steam, tried using protontricks, lutris, and steamtinkerlaunch to get past this bug and nothing is working. Really dont want to use wine steam as it breaks FFB on my wheel.
