### ISSUE TITLE
Launch the steam app instead of exe file (for steam overlay and more)

### ISSUE THREAD

**Issue by jacobcargen** [BeamMP/BeamMP-Launcher#34]
i would like for the game to launch the steam app rather than the application file. This would be nice so that it logs my hours, I can get steam overlay, and more steam features.

I'm sure there are a few different ways to do this, I cannot really think of many though.

The current solution of launching the launcher version then the steam version has stopped working for me, so this feature would be quite nice.

**Comment by Mack29446** [comment]
Hi, this is already implemented in launcher v3, which is currently in early-access testing :D

**Comment by jacobcargen** [comment]
Oh, thanks for letting me know. I was not informed.
