### ISSUE TITLE
Legit version showing up as cracked

### ISSUE THREAD

**Issue by isfot** [BeamMP/BeamMP-Launcher#4]
My humble bundle version of the game does not work with this mod

**Comment by Starystars67** [comment]
Hi there, When purchasing the game though humble bundle they should have offered you a steam key too. If not you can request it from them and they will provide it.

**Comment by DonFlymoor** [comment]
I have the same problem. The solution should NOT be to use steam instead of humble, it should be to support humble bundle versions as well.

**Comment by Starystars67** [comment]
> I have the same problem. The solution should NOT be to use steam instead of humble, it should be to support humble bundle versions as well.

Hi there @DonFlymoor . The humble bundle version has no way for us to confirm legitimacy. Hence why we use the steam variant. Note that they provide the steam key at no extra cost. 

I would say that the proposed solution is extremely fair as it puts no extra costs on anyone and ensures game legitimacy. Bottom line is that Humble Bundle have included a steam key for whatever reason and it works perfectly in this case. 
Though it seems you might not like the solution does not make it necessarily wrong.

**Comment by DonFlymoor** [comment]
While I understand where you are coming from, BeamNG made the decision to be drm free, and it doesn't make sense to make a mod which uses drm when the game itself does not have it.

**Comment by DonFlymoor** [comment]
The new version works with the Humble Bindle version! Thanks!

**Comment by Starystars67** [comment]
> The new version works with the Humble Bundle version! Thanks!

Sorry for the slow reply here. Yes we pushed an update that should solve the issue for you. Sorry for not replying back here on that matter.

I will close this issue now.
