### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Alfagun74** [BeamMP/BeamMP-Launcher#5]
So far i can get this up and running with Wine but i get this Error:

![image](https://user-images.githubusercontent.com/22225051/111086302-aa238d80-851b-11eb-877e-501c56dc0ea2.png)

Are there any Plans for Linux Support?

**Comment by Anonymous-275** [comment]
Hello! yes linux support is planned and i just recently pushed a crash fix for that

**Comment by Starystars67** [comment]
@Alfagun74 please try the latest version that we pushed. Hopefully your issue should be resolved now.

If it is not please comment back and I will reopen this issue.
