### ISSUE TITLE
[Bug] Not able to change BeamNG launch directory

### ISSUE THREAD

**Issue by WillXProject** [BeamMP/BeamMP-Launcher#50]
my BeamNG is located in an external drive, is there a way to change the directory to the drive?
I do own a legal copy of BeamNG

**Comment by 20dka** [comment]
Hey, the launcher should detect the game path based on your registry, as long as you've launched it once. What version is your game, what error code does the launcher give?

**Comment by WillXProject** [comment]
> Hey, the launcher should detect the game path based on your registry, as long as you've launched it once.

Fixed, thanks :D
