### ISSUE TITLE
[Bug] Error in serverlist: The game is not connected to the Launcher

### ISSUE THREAD

**Issue by O1LER** [BeamMP/BeamMP-Launcher#55]
**Describe the bug**
While in the serverlsit, the game shows an error, not connected to the launcher.
Despite the launcher being up and running, without errors and saying: Game connected!

**To Reproduce**
Unknown

To solve the issue, it is enough to log out and log back in, without needing to even restart the game

**Expected behavior**
While the launcher is running and showing connected, the game should also be connected to the launcher

**Screenshots**
![image](https://user-images.githubusercontent.com/44237025/209407870-9ed1bce2-a915-4435-9681-52500952790d.png)
![image](https://user-images.githubusercontent.com/44237025/209407883-16d55bf9-5136-4146-bb23-266b41364af7.png)

[beamng.log](https://github.com/BeamMP/BeamMP/files/10297432/beamng.log)

**Comment by Anonymous-275** [comment]
Fix in V3

**Comment by O1LER** [comment]
So its a launcher issue despite the launcher being ok and without error?

**Comment by Anonymous-275** [comment]
> So its a launcher issue despite the launcher being ok and without error?

It is a shared issue that is only fixable by eliminating the local socket method used in V2

**Comment by Anonymous-275** [comment]
So the only fix is to change that method

**Comment by Anonymous-275** [comment]
Please reopen if this persits in 2.1.0

**Comment by ColbyMMMM** [comment]
Hello, I'm having the same bug as stated above. and the to solve it is the same way,

ive also tried opening up my firewall, reinstalling Windows changing ports for the game and launcher, and even trying another ISP, and it's still getting blocked.

**Comment by WiserTixx** [comment]
@ColbyMMMM Could you make a game support ticket in [our discord server](https://discord.gg/BeamMP)?

**Comment by ColbyMMMM** [comment]
> [@ColbyMMMM](https://github.com/ColbyMMMM) Could you make a game support ticket in [our discord server](https://discord.gg/BeamMP)?

done discord is colby.
