### ISSUE TITLE
[Linux] Connecting to modded servers fail as the download nears 100%

### ISSUE THREAD

**Issue by JoshuaFern** [BeamMP/BeamMP-Launcher#59]
When connecting to any modded server, connection fails after the download nears 100% completed.
Actually disconnects from BeamMP entirely, which I restart the game to remedy. 

This is running under Proton on Linux.

Client Log: https://rentry.co/beammp-linux
Server Log (Separate attempt, on another server): https://cdn.discordapp.com/attachments/1030982141808492578/1141283517372833852/image.png

Possibly related to https://github.com/BeamMP/BeamMP-Launcher/issues/47

**Comment by OfficialLambdax** [comment]
Is the splitload error (after the Altitude.zp request) happening before or after this **v**
> Loading Resource **1/1**: /UtahExtraDS.zip

Also i notice that the client only seems to know about a single mod. How many mods are on that server?

**Comment by O1LER** [comment]
@OfficialLambdax the logs are from two different servers, so one might only have altitude.zip and the other only utahExtra.zip

@JoshuaFern can you provide full logs of both server and launcher, both from the same connection attempt?

**Comment by JoshuaFern** [comment]
@O1LER I can't yet do that yet because I need to run a server locally to do so (the screenshot of the log was from a friend's server). Whenever I try to generate an authkey on the website I get an error: `Cannot POST /k/keys`

I'm going to keep trying for an authkey and work with my friend for further logs when he's available.

**Comment by O1LER** [comment]
AFAIK 'Cannot POST /k/keys' happens due to an issue on the browser. Try another browser or device
https://beammp.com/k/keys

Dont know about problems with writing the log. Might this be a proton or a hardware limitation? As in, both copying the mod zip after download and writing the log fast enough is hitting some troughput limit or something?

**Comment by JoshuaFern** [comment]
I fixed it, but don't ask me how. I just started deleting stuff and letting it repopulate.
