### ISSUE TITLE
[Bug] beammp launcher is trying to write to my old user filename

### ISSUE THREAD

**Issue by Hoshimi-Draws** [BeamMP/BeamMP-Launcher#6]
**Have you read our FAQ/Wiki/#before-you-ask ?**
No

**Describe the bug**
beammp launcher is trying to write to my old username (I've changed the user file name) gives me an access denied... as the file doesn't exist.

**To Reproduce**
1. have a windows user profile with a changed user filename
2. install beammp normally
3. launch beammp
4. error ([16/5/2021 07:35:14] [FATAL] create_directories: Access is denied.: "C:\Users\**_|MY OLD USER FILENAME|_**\AppData\Local\BeamNG.drive\0.22\mods/multiplayer")

**Expected behavior**
the beammp launcher to launch beammp

**Screenshots**
error v
![image](https://user-images.githubusercontent.com/84279282/118401308-10ab5180-b61a-11eb-906a-a537733ead54.png)
normal instalation stuff v
![image](https://user-images.githubusercontent.com/84279282/118401377-4819fe00-b61a-11eb-8283-3822bb5c9602.png)

**Desktop (please complete the following information):**
 - OS + Version: windows 10 pro
 - Browser (If applicable): Crome

**Additional context**
I think this could be fixed with a command in the "Launcher.cfg" file under "C:\Users\hoshi\AppData\Roaming\BeamMP Launcher" but at the moment I don't know the prompt to add before the correct address of beamngdrive. ("C:\Users\hoshi\AppData\Local\BeamNG.drive\0.22\mods/multiplayer")

**Comment by Thiritin** [comment]
> 4\. error ([16/5/2021 07:35:14] [FATAL] create_directories: Access is denied.: "C:\Users**_|MY OLD USER FILENAME|_**\AppData\Local\BeamNG.drive\0.22\mods/multiplayer")

Tried, did not work sadly. I checked and the %userprofile% env var that is used in the reg keys is also set to my new user folders path corectly.

**Comment by Anonymous-275** [comment]
The launcher reads from your windows registry the key "Local appdata" under "HK Current User\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders", if that is wrong then you need to fix it manually

**Comment by ShyLena** [comment]
Can u explain what exactly needs to be changed? i still cant get it to work with the current information.

**Comment by Hoshimi-Draws** [comment]
> Can u explain what exactly needs to be changed? i still cant get it to work with the current information.

not sure if this is what @Anonymous-275 ment, but I'm pretty sure this is the file that needs editing, to what it needs to be set to? no idea, I don't do well with rigedit...
![image](https://user-images.githubusercontent.com/84279282/150464373-23d0c902-aea2-4959-ba70-6ce2ee37beac.png)

**Comment by Anonymous-275** [comment]
Tha key dif you double click it, you can edit the value head over to your local appdata and copy the path then paste it here

**Comment by ShyLena** [comment]
Ty, got everything up and running.

**Comment by Anonymous-275** [comment]
np this registry issue should be resolved in v3.0 when it releases glad this temporary fix worked

**Comment by L33TIFYxd** [comment]
> Tha key dif you double click it, you can edit the value head over to your local appdata and copy the path then paste it here

I changed the path in the registry and im getting a new error now 
Failed to open file directory: C:\Users\Mads J°rgensen\AppData\Local\BeamNG.drive\0.28\mods\multiplayer\BeamMP.zip
Anyone got any ideas??

**Comment by JUGGZ0121** [comment]
> Tha key dif you double click it, you can edit the value head over to your local appdata and copy the path then paste it here

What exactly do I need to put in there?

**Comment by Kaici123** [comment]
@Anonymous-275 Where do I find it this time?

**Comment by Kaici123** [comment]
Тo put it out there
