### ISSUE TITLE
Linux: Failed to read link

### ISSUE THREAD

**Issue by UltraBlackLinux** [BeamMP/BeamMP-Launcher#61]
So I've been experimenting with the BeamMP launcher on linux, but I'm facing the following issue

![image](https://github.com/BeamMP/BeamMP-Launcher/assets/62404294/9cdb2707-188c-496a-b408-6970f8793a33)

I have checked the config file, which was for some reason pointing at the wrong directory? (using my linux login name instead of `steamuser`), but even after fixing that (changed to `C:\users\steamuser\AppData\Local\BeamNG.drive`) I still get the error. The link file doesn't seem to be corrupted or anything like that, so any idea what else I could try?

**Comment by Anonymous-275** [comment]
it tries to read C:\Users\[user]\AppData\Local\BeamNG.drive\latest however if the ProfilePath in the toml config is set it should use that,

you can try and set it to C:\Users\[user]\AppData\Local\BeamNG.drive or whatever path your have for your user config

**Comment by UltraBlackLinux** [comment]
I did an oopsie and accidentally launched proton with `/pfx` at the end of the compatdata path. You're not supposed to do that. All that did was create another wineprefix inside of the wineprefix, which was the source of all problems
