### ISSUE TITLE
Mods not loading up on Mac CrossOver

### ISSUE THREAD

**Issue by enzofrnt** [BeamMP/BeamMP-Launcher#83]
Hi,

I'm currently running the game through Crossover on macOS. I'm not sure why, but the multiplayer mod isn't loading properly. If I manually place the BeamMP mods in the default mod folder of my game, everything works fine. However, if I don't do this, the multiplayer mode never shows up in the game.

I'm available to perform any necessary tests.

Thanks.

**Comment by Always1needs1help** [comment]
Hey mine doesn't work, after I placed the files from beammp can you help ?

**Comment by enzofrnt** [comment]
Any news here ?
