### ISSUE TITLE
"[FATAL] Cannot get Local Appdata directory!"

### ISSUE THREAD

**Issue by SirStrategic** [BeamMP/BeamMP-Launcher#9]
When running the launcher I had experienced the error message:
"[FATAL] Cannot get Local Appdata directory!"

I found the place where the exception is thrown in the code, it is in GameStart.cpp
[https://github.com/BeamMP/BeamMP-Launcher/blob/master/src/GameStart.cpp](https://github.com/BeamMP/BeamMP-Launcher/blob/master/src/GameStart.cpp)

In my case (and allegedly a few others') this is due to the windows registry key used (seen in line 30):
`        sk = R"(SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders)";`

The key: "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" **is deprecated and not found in a few systems.** In my case I had to get a copy of the Shell Folders key and modify it slightly (change name of user in the path values) so that beammp may work.

This is all I know about the issue as I do not know too much more about programming. 

Update: I went back and read a note included in the registry (obtained from my friend who I am certain did not include the following note himself) and found the following:
![image](https://user-images.githubusercontent.com/47442790/133925478-9f2273df-ea27-40fc-bde3-44f30b0cd448.png)
...hope it helps :)

**Comment by Starystars67** [comment]
Interesting find @SirStrategic !
I have assigned @Anonymous-275 to this issue as he is the original creator of the launcher.

**Comment by Anonymous-275** [comment]
Love it when windows deprecates things I use, I will address this issue with the appropriate fixes when I get to it, thank you for the report

**Comment by Floffys** [comment]
How the hell do you get access to the shell folder keys

**Comment by SirStrategic** [comment]
I believe my friend gave it to me from his computer.
